export const COLOR = {
    BUTTERFLY_VIOLET: '#585292',
    LAVENDER_VIOLET: '#8a85b2',
    NEWYORK_PINK: '#E07C7C',
    SHILO_PINK: '#EBB9B8',
    SOLID_WHITE: '#FFF',
    SILVER_GRAY : '#BCBCBC',
    CHALICE_GRAY : '#A9A9A9',
    WILDSAND_GRAY : '#F5F5F5',
    SANTAS_GRAY : '#9796A8',
    MINESHAFT_GRAY : '#3B3B3B',
    DARK_GRAY: '#2E2E2E',
    SOLID_BLACK: '#000',
}